version: "3.1"

services:
  pgadmin-dev:
    container_name: pgadmin-dev
    image: chorss/docker-pgadmin4:latest
    ports:
      - 5001:5050
    networks:
      - frontend
      - backend
    links:
      - db-service:postgres

  pghero-dev:
    container_name: pghero-dev
    image: bmorton/pghero
    ports:
      - 5002:8080
    networks:
      - frontend
      - backend
    links:
      - db-service:db
    environment:
      - DATABASE_URL=postgres://postgres:psqlpass@db:5432

  kafka-manager-dev:
    container_name: kafka-manager-dev
    image: sheepkiller/kafka-manager
    ports: 
      - "5003:9000"
    networks:
      - frontend
      - backend
    links:
      - zookeeper-service:zk
    environment:
      ZK_HOSTS: "zookeeper-service:2181"
      APPLICATION_SECRET: letmein